# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SDCS.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nSDCS.proto\"\x12\n\x03key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x04\x64\x61ta\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2!\n\x04SDCS\x12\x19\n\x08\x66inddata\x12\x04.key\x1a\x05.data\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SDCS_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEY']._serialized_start=14
  _globals['_KEY']._serialized_end=32
  _globals['_DATA']._serialized_start=34
  _globals['_DATA']._serialized_end=68
  _globals['_SDCS']._serialized_start=70
  _globals['_SDCS']._serialized_end=103
# @@protoc_insertion_point(module_scope)
